"""add professional portfolio images

Revision ID: d4efe51535c2
Revises: 61551d38358c
Create Date: 2026-02-27 13:16:58.424767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4efe51535c2'
down_revision: Union[str, Sequence[str], None] = '61551d38358c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_portfolio_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_portfolio_images_professional_profile_id'), 'professional_portfolio_images', ['professional_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_portfolio_images_professional_profile_id'), table_name='professional_portfolio_images')
    op.drop_table('professional_portfolio_images')
    # ### end Alembic commands ###
