"""add view_count to professional_profiles

Revision ID: 16ab64449688
Revises: 500368440d67
Create Date: 2026-03-08 14:05:07.242316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ab64449688'
down_revision: Union[str, Sequence[str], None] = '500368440d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_profiles', sa.Column('view', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional_profiles', 'view')
    # ### end Alembic commands ###
