"""add revolut and wise tags to professional profile

Revision ID: 174310aa4e6c
Revises: dc49985c1b72
Create Date: 2026-03-24 15:50:41.771154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174310aa4e6c'
down_revision: Union[str, Sequence[str], None] = 'dc49985c1b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_profiles', sa.Column('revolut_tag', sa.String(length=100), nullable=True))
    op.add_column('professional_profiles', sa.Column('wise_tag', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional_profiles', 'wise_tag')
    op.drop_column('professional_profiles', 'revolut_tag')
    # ### end Alembic commands ###
