"""add reports table

Revision ID: 500368440d67
Revises: e07d8ec1bdb4
Create Date: 2026-03-06 17:05:54.306872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500368440d67'
down_revision: Union[str, Sequence[str], None] = 'e07d8ec1bdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'fake', 'inappropriate', 'offensive', 'other', name='report_reason'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'dismissed', name='report_status'), server_default='pending', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=True),
    sa.Column('reported_review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reported_review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_user_id', 'reported_review_id', name='uq_report_review'),
    sa.UniqueConstraint('reporter_user_id', 'reported_user_id', name='uq_report_profile')
    )
    op.create_index(op.f('ix_reports_reported_review_id'), 'reports', ['reported_review_id'], unique=False)
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_review_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
