"""add reviews table

Revision ID: 61551d38358c
Revises: 16fc737019fb
Create Date: 2026-02-21 08:37:18.749590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61551d38358c'
down_revision: Union[str, Sequence[str], None] = '16fc737019fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_user_id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_user_id', 'customer_user_id', name='unique_customer_review')
    )
    op.create_index(op.f('ix_reviews_customer_user_id'), 'reviews', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_reviews_professional_user_id'), 'reviews', ['professional_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_professional_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_user_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
