"""rename view to view_count in professional_profiles

Revision ID: dc49985c1b72
Revises: 16ab64449688
Create Date: 2026-03-08 14:09:06.602142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc49985c1b72'
down_revision: Union[str, Sequence[str], None] = '16ab64449688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_profiles', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('professional_profiles', 'view')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_profiles', sa.Column('view', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('professional_profiles', 'view_count')
    # ### end Alembic commands ###
