"""add suggestions to categories

Revision ID: e07d8ec1bdb4
Revises: d4efe51535c2
Create Date: 2026-03-04 23:50:50.576525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07d8ec1bdb4'
down_revision: Union[str, Sequence[str], None] = 'd4efe51535c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('professional_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_user_id', 'professional_user_id', name='uq_customer_professional')
    )
    op.create_index(op.f('ix_favorites_customer_user_id'), 'favorites', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_favorites_professional_user_id'), 'favorites', ['professional_user_id'], unique=False)
    op.add_column('categories', sa.Column('suggestions', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'suggestions')
    op.drop_index(op.f('ix_favorites_professional_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_customer_user_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
